### ISSUE TITLE
Null output...

### ISSUE THREAD

**Issue by Merovex** [olegtarasov/get-tag#6]
So, just trying this for the first time. There is no output.

**Comment by olegtarasov** [comment]
@Merovex Hi! Are you still experiencing this problem? Please share your action config so we could start figuring out what went wrong.

**Comment by mandytrinh** [comment]
Hi,
I'm also seeing this prints out a blank string
Here's my config

```
name: Test
on:
  push:
    branches:
      - test-branch
    tags: 
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get git tag
      uses: olegtarasov/get-tag@v2
      id: tagName
      with:
        tagname: ${{ steps.tagName.outputs.tag }}
    - name: Echoes tag
      run: echo tag is ${{ steps.tagName.outputs.tag }}
```

neither `echo tag is ${{ steps.tagName.outputs.tag }}` nor `echo tag is ${GIT_TAG_NAME}` prints anything
